#ifndef PCH_H
#define PCH_H

#endif // PCH_H
// Add C includes here

#if defined __cplusplus
// Add C++ includes here
#include <QMainWindow>
#include <QString>
#include <QEvent>
#include <QSystemTrayIcon>
#include <QLocale>
#include <QGraphicsBlurEffect>
#include <QShortcut>
#include <QtConcurrentRun>
#include <QThread>
#include <QValidator>
#include <QFrame>
#include <QSpacerItem>
#include <QStandardItemModel>
#include <QStandardItem>
#include <QSqlTableModel>
#include <QFutureWatcher>
#include <QDialog>
#include <QKeyEvent>
#include <QMouseEvent>
#include <QMessageBox>
#include <QtConcurrent>
#include <QFuture>
#include <QCompleter>
#include <QList>
#include <QPair>
#include <QComboBox>
#include <QFileDialog>
#include <QMenu>
#include <QTextEdit>
#include <QAction>
#include <QApplication>
#include <QCalendarWidget>
#include <QObject>
#include <QTextStream>
#include <QStandardItemModel>
#include <QXmlStreamReader>
#include <QDomDocument>
#include <QDir>
#include <QSettings>
#include <QCryptographicHash>
#include <QSortFilterProxyModel>
#include <QSqlQueryModel>
#include <QWidget>
#include <QToolButton>
#include <QColor>
#include <QGridLayout>
#include <QDate>
#include <QCoreApplication>
#include <QEventLoop>
#include <QMovie>
#include <QCloseEvent>
#include <QStyledItemDelegate>
#include <QHeaderView>
#include <QRegExp>
#include <QScrollBar>
#include <QIcon>
#include <QFileSystemWatcher>
#include <QtSql>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QTableView>
#include <QItemDelegate>
#include <QLineEdit>
#include <QFile>
#include <QFileInfo>
#include <QtNetwork>
#include <QNetworkAccessManager>
#include <QNetworkRequest>
#include <QNetworkReply>
#include <QSslError>
#include <QTimer>
#include <QUrl>
#include <QStringListModel>
#include <QDesktopServices>
#include <QtNetwork/QTcpSocket>
#include <QVector>
#include <QImage>
#include <QPixmap>
#include <QBuffer>
#include <QImageReader>
#include <QDesktopWidget>
#include <QRect>
#include <QAbstractItemView>
#include <QPropertyAnimation>
#include <QFontComboBox>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsItem>
#include <QVersionNumber>
#include <QGraphicsDropShadowEffect>
#include <QRegExpValidator>
#include <QPrintPreviewDialog>
#include <QPrinter>
#include <QToolBar>
#include <QPushButton>
#include <QSpinBox>
#include <QDateTimeEdit>
#include <QSound>
#endif
