// This is an open source non-commercial project. Dear PVS-Studio, please check it.

// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com

#ifndef STATICSTRINGS_H
#define STATICSTRINGS_H
#define _speciality "speciality"
#define _autoCompleteByWord "autoCompleteByWord"
#define _showChronicConditions "showChronicConditions"
#define _showNavArrows "showNavArrows"
#define _smallScreenMode "smallScreenMode"
#define _simpleExamination "simpleExamination"
#define _alwaysSave "alwaysSave"
#define _inLinePatientList "inLinePatientList"
#define _autosaveinterval "autosaveinterval"
#define _autoSave "autoSave"
#define _minimizeToTray "minimizeToTray"
#define _autoClosePrintDlg "autoClosePrintDlg"
#define _enableVisualEffects "enableVisualEffects"
#define _updateNotify "updateNotify"
#define _useToast "UseToastNotificationSystem"
#define _usePhotoViewer "usePhotoViewer"
#define _remmberLastFollowupDate "remmberLastFollowupDate"

#define _Prices "Prices"
#define _newVisitPrice "newVisitPrice"
#define _followVisitprice1 "followVisitprice1"
#define _followVisitprice2 "followVisitprice2"
#define _followVisitprice3 "followVisitprice3"
#define _followVisitprice4 "followVisitprice4"

//print settings
#define _paperSizeId "paperSizeId"
#define _pageMargin "pageMargin"
#define _showBanner "showBanner"
#define _showDrugs "showDrugs"
#define _showInvsestigations "showInvestigations"
#define _showMeasurments "showMeasurments"
#define _showDrugsTableOutline "showDrugsTableOutline"
#define _drugsPrintMode "drugsPrintMode"
#define _showDrugsTitle "showDrugsTitle"
#define _showHeader "showPrescriptionHeader"
#define _showFooter "showPrescriptionFooter"
#define _showLogo "showPrescriptionLogo"
#define _bannerStyle "prscriptionBannerStyle"
#define _logoSize "logoPixelSize"

#define _headerHeightPercent "headerHeightPercent"
#define _footerHeightPercent "footerHeightPercent"
#define _bannerHeightPercent "bannerHeightPercent"
#define _bannerFont "bannerFont"
#define _bannerFontSize "bannerFontSize"
#define _bannerFontBold "bannerFontBold"
#define _roshettaFont "roshettaFont"
#define _roshettaFontSize "roshettaFontSize"
#define _roshettaFontBold "roshettaFontBold"
#define _doseFont "doseFont"
#define _doseFontSize "doseFontSize"
#define _doseFontBold "doseFontBold"
#define _requestsFont "requestsFont"
#define _requestsFontSize "requestsFontSize"
#define _requestsFontBold "requestsFontBold"
#define _measurementsFont "measurementsFont"
#define _measurementsFontSize "measurementsFontSize"
#define _measurementsFontBold "measurementsFontBold"
#define _signatureFont "signatureFont"
#define _signatureFontSize "signatureFontSize"
#define _signatureFontBold "signatureFontBold"
#define _showDrugsInitDate "showDrugsInitDate"
#define _showSignaturePrintedOn "showSignaturePrintedOn"
#define _showOnlyNewlyModifiedAddedDrugs "showOnlyNewlyModifiedAddedDrugs"
#define _showTradeNamesBold "showTradeNamesBold"
#define _showDoseNewLine "showDoseNewLine"
#define _preferArabic "prefereArabic"
#define _showStartDate "showStartDate"
#define _enableFullPage "enableFullPage"
#define _enableBodyHeaderSeparator "enableBodyHeaderSeparator"
#define _compactMode "compactMode"
//#define _showHorizontalLineBelowHeader "showHorizontalLineBelowHeader"

#define _Fonts "Fonts"
#define _defaultFont "defaultFont"
#define _defaultFontSize "defaultFontSize"
#define _defaultFontBold "defaultFontBold"

#define _textboxFont "textboxFont"
#define _textboxFontSize "textboxFontSize"
#define _textboxFontBold "textboxFontBold"

#define _clinic "Clinic"
#define _maxFollowUps "maxFollowUps"
#define _maxFollowUpsPerProblem "maxFollowUpsPerProblem"
#define _autoSetnewAfterMaxPerProblemIsReached "autoSetnewAfterMaxPerProblemIsReached"

#define _checkOut "CheckOut"
#define _checkoutDate "checkoutDate"
#define _checkoutTime "checkoutTime"

#define _printWin "PrinterWindow"
#define _printWinWidth "printWinWidth"
#define _printWinHeight "printWinHeight"

#define _dbOptions "dbOptions"
#define _autovacuum "autovacuum"
#define _optimize "optimize"
#define _WAL_checkPoint "WALCheckPoint"
#define _shrinkMemory "shrinkMemory"
#define _shared_cache "shared_cache"
#define _temp_store "temp_store"
#define _synchronous "synchronous"
#define _journal_mode "journal_mode"
#define _locking_mode "locking_mode"
#define _cache_size "cache_size"
#define _page_size "page_size"

#define _selectedTheme "selectedTheme"

#define _th_window "th_window"
#define _th_subwindow "th_subwindow"
#define _th_button "th_button"
#define _th_input "th_input"
#define _th_elementtext "th_elementtext"
#define _th_inputtext "th_inputtext"
#define _th_list "th_list"

#define _th_top_color "top_color"
#define _th_bottom_color "bottom_color"
#define _th_border_color "border_color"
#define _th_border_width "border_width"
#define _th_border_radius "border_radius"
#define _th_color_normal "color_normal"
#define _th_color_hover "color_hover"
#define _th_color_focus "color_focus"
#define _th_color_disabled "color_disabled"
#define _th_color_warning "color_warning"
#define _th_color_error "color_error"
#define _th_border_color_normal "border_color_normal"
#define _th_border_color_hover "border_color_hover"
#define _th_border_color_focus "border_color_focus"
#define _th_border_color_diabled "border_color_diabled"
#define _th_selected_item_color "selected_item_color"
#define _th_toolbutton_color "toolbutton_color"
#define _th_messagebox_background_color "messagebox_background_color"
#define _th_messagebox_text_color "messagebox_text_color"
#define _th_enable3D "enable3D"
#define _th_selected_item_text_color "selected_item_text_color"

#endif // STATICSTRINGS_H
